export const settings = $state({
  layout: 'strip',
  theme: 'off',
  bg: 'paper',
  filter: 'none',
  shape: 'rounded',
  shots: 4,
  timer: 3,
  bgIntensity: 70,
  themeIntensity: 75,
  gap: 16,
  fps: 6,
  caption: '',
  dateOn: true,
  mirrorOn: true,
});
